### PR TITLE
Dynamics page for OAuth redirects

### PR DESCRIPTION
**Pull request by acoumb**
This PR contains the Dynamics integration dedicated page for handling OAuth redirects. 
It will handle `dynamics:oauth:success` message sent by the `window.opener` interface.

### CODE REVIEW

**Review by AndyButland — COMMENTED** [review]
This looks fine.  I've realised though that if and when you release this, it'll break existing versions of the Dynamics integration, as they will be expecting a message with the prefix "hubspot".

If I've understood that right, perhaps it means you can't update this.  I'll leave it with you to consider, but if not, then we'll just have to live with it.

**Comment by acoumb** [comment]
I don't think it will break the existing versions, as they will continue to use `https://hubspot-forms-auth.umbraco.com/` and watch for `hubspot:oauth:success` message. Only the new version of the Dynamics package will use `https://hubspot-forms-auth.umbraco.com/oauth/dynamics/` and have the `message` event listener watch for `dynamics:oauth:success`.

The other update I will need to make is to the `Umbraco Integrations` Azure app to support the additional redirect URI.
image

**Review by AndyButland — COMMENTED** [review]
Looks good, but there's a couple of things I haven't followed - could you check or explain please?

- Why do I not see a "Semrush" page in this repo, even though that looks to be responding to a specific message (e.g. `semrush:oauth:success`).
- Why do you say you need to add a new redirect to the Azure app, even though there isn't one for Semrush, Google and Shopify?

**Comment by acoumb** [comment]
- for Semrush I am passing a relative URL as redirect (/oauth/umbraco/success), the integration is not using the `OAuth Proxy`. If I remember correctly they took care of all the setup.
- only for Dynamics I modified the key from `hubspot:oauth:success` to `dynamics:oauth:success` and updated the proxy endpoint, the others are ok. Dynamics is using an Azure App called `Umbraco Integrations`.

**Review by AndyButland — APPROVED** [review]
OK then, thanks. Sounds like you have all the bases covered.

**Pull request merged**
